# Extra env variables
# env = MY_GLOBAL_ENV,setting

# Bibata cursor theme
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24

# Fix for JetBrains IDEs (PhpStorm, IntelliJ, etc.) on Wayland
env = _JAVA_AWT_WM_NONREPARENTING,1
